### ISSUE TITLE
“否”字位置错了

### ISSUE THREAD

**Issue by dxinef** [silaLi/pinyin#1]
https://github.com/silaLi/pinyin/blob/f40b0b5c16f292f1f008c7a0005f78591e1c8afb/chinese.js#L88
https://github.com/silaLi/pinyin/blob/f40b0b5c16f292f1f008c7a0005f78591e1c8afb/chinese.js#L89

“否”字位置错了，应该为 fou
“佛”字一般读 fo 的时候比较多

**Comment by liyang-fly** [comment]
已修改
